# Generated by Django 5.2.8 on 2025-11-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='test',
            new_name='text',
        ),
    ]
